version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    image: book_catalog:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://job1_sewb_user:yfnlzYOKeUCgXiL7Lij9cZUtjiCRq8FB@dpg-crjeg05ds78s73eafu40-a.singapore-postgres.render.com/job1_sewb
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    image: inventory_management:latest
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://job1_sewb_user:yfnlzYOKeUCgXiL7Lij9cZUtjiCRq8FB@dpg-crjeg05ds78s73eafu40-a.singapore-postgres.render.com/job1_sewb
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: job1_sewb_user
      POSTGRES_PASSWORD: yfnlzYOKeUCgXiL7Lij9cZUtjiCRq8FB
      POSTGRES_DB: job1_sewb
    ports:
      - "5432:5432"